pravega/pravega-client-rust

README.md

Fix pravega url.

---

.github/workflows/build_wheel.py
.github/workflows/documentation.yml
.github/workflows/tagPublish.yml
bindings/Cargo.toml
bindings/Readme.md

Fix hyperlink for API documentation on master branch.
Fixes #208 
- Fix hyperlink for API documentation on master branch. 
- Ensure python binding artifacts are generated for Python 3.8, 3.9
- Ensure the documentation that is published at pypi repo has more details.
Ensure cargo docs for master is visible via link https://pravega.github.io/pravega-client-rust/doc/index.html
Updated docs @ https://test.pypi.org/project/pravega/

Issue 208: Fix Bug in documentation.

---

.github/workflows/documentation.yml

Upgrade mdbook
Fixes #213 
see https://blog.rust-lang.org/2021/01/04/mdbook-security-advisory.html
The existing tests should continue to pass.

Issue 213: Upgrade mdbook

---

benches/benchmark.rs
bindings/Cargo.toml
bindings/src/stream_manager.rs
examples/event_write_and_read.rs
integration_test/src/event_stream_reader_tests.rs
integration_test/src/tablemap_tests.rs
integration_test/src/tablesynchronizer_tests.rs
src/client_factory.rs
src/event_reader.rs
src/event_reader_group.rs
src/reader_group/reader_group_state.rs
src/table_synchronizer.rs
src/tablemap.rs

Table map should use segment under the a user configured scope
Fix #217 
Let user pass a scope when creating the table map.
Test should pass

Issue 217: Table map uses wrong scope

---

CHANGELOG.md
Cargo.toml
README.md
bindings/Cargo.toml

Prepare v0.1.0 release

---

CHANGELOG.md
Cargo.toml
auth/Cargo.toml
benches/benchmark.rs
book/src/Python/PythonBindings.md
book/src/Python/contribution.md
book/src/Rust/Readme.md
book/src/index.md
book/src/quickStart.md
channel/Cargo.toml
config/Cargo.toml
connection_pool/Cargo.toml
controller-client/Cargo.toml
examples/Cargo.toml
examples/event_write_and_read.rs
python_binding/Cargo.toml
retry/Cargo.toml
shared/Cargo.toml
src/lib.rs
wire_protocol/Cargo.toml

Prepare 0.2 release

---

.github/workflows/cibuild.yml
book/src/Rust/ByteClient.md
connection_pool/src/connection_pool.rs
python_binding/README.md
src/byte/writer.rs

CI didn't include connection pool.
Some other minor fixes.

Fix connection pool, CI, and some docs

---

Cargo.toml
auth/Cargo.toml
channel/Cargo.toml
config/Cargo.toml
connection_pool/Cargo.toml
controller-client/Cargo.toml
examples/Cargo.toml
macros/Cargo.toml
pravegactl/Cargo.toml
python_binding/Cargo.toml
retry/Cargo.toml
shared/Cargo.toml
wire_protocol/Cargo.toml

Update version of all the modules to 0.3.0.
Fixes #325
Update version of all the modules to 0.3.0.
No changes to the functionality. Ensure all the build checks pass.

Issue 325: Update version to 0.3.0

---

retry/src/lib.rs
retry/src/retry_async.rs
retry/src/retry_result.rs
retry/src/retry_sync.rs

Add Retry Error
#133 
Implements retry_error
Usual testing

Retry Error

---

src/event/reader_group_state.rs

Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>
Make reader offline idempotent
Fixes #327
If reader offline is called and the reader is already offline no update is performed.

Issue #327: Make reader offline idempotent

---

Cargo.toml
auth/Cargo.toml
book/src/index.md
channel/Cargo.toml
config/Cargo.toml
connection_pool/Cargo.toml
controller-client/Cargo.toml
examples/Cargo.toml
macros/Cargo.toml
python_binding/Cargo.toml
retry/Cargo.toml
shared/Cargo.toml
wire_protocol/Cargo.toml

Update version to 0.3.1
Fixes #334
Update version to 0.3.1 to prepare for release.
No changes to functionality, all the existing tests should pass.

Issue 334: Update version to 0.3.1

---

book/src/Rust/ByteClient.md
python_binding/src/stream_manager.rs
python_binding/src/stream_writer.rs
python_binding/src/transaction.rs
src/byte/reader.rs
src/event/reader.rs

* Fix the code snips
FIxes #343
* Fix the code snips
All the existing tests should continue to pass.

Issue 343: Fix Byte Client sample code snips

---

src/event/reader.rs
src/event/reader_group_state.rs

To fix the problem in the comment

remove redundant sync check

---

src/event/reader.rs
src/event/reader_group_state.rs
src/sync/table.rs

To accommodate the last comment of #342

add private function for retry

---

config/src/credentials.rs
config/src/lib.rs
integration_test/src/pravega_service.rs
integration_test/src/transactional_event_writer_tests.rs
shared/src/naming_utils.rs
src/event/reader_group_state.rs
src/sync/table.rs
src/util/oneshot_holder.rs
wire_protocol/src/connection.rs
wire_protocol/src/wire_commands.rs

fix clippy error

---

controller-client/src/lib.rs
integration_test/src/disconnection_tests.rs
retry/Cargo.toml
retry/src/retry_async.rs
retry/src/retry_policy.rs
retry/src/retry_sync.rs

* Re-implement the retry policy
* Add initial delay
* Add max delay
* Add max attempt
* Add expiration time
* Add tests
Fixes #359

Properly implement the retry policy

---

Cargo.toml
auth/Cargo.toml
book/src/index.md
channel/Cargo.toml
config/Cargo.toml
connection_pool/Cargo.toml
controller-client/Cargo.toml
examples/Cargo.toml
golang/Cargo.toml
macros/Cargo.toml
pravegactl/Cargo.toml
python/Cargo.toml
retry/Cargo.toml
shared/Cargo.toml
wire_protocol/Cargo.toml

Update version to 0.3.2
Fixes #381 
Update version to 0.3.2 to prepare for release.
All tests pass

Issue 381: Update version to 0.3.2

---

nodejs/package-lock.json
nodejs/package.json

Fix nodejs/npm publish workflow.
Fixes #393 
Downgrade jest.
The job runs correctly https://github.com/thekingofcity/pravega-client-rust/runs/7786153623?check_suite_focus=true

Issue 393: Failed workflow `nodejs-npm`

---

nodejs/README.md

As the wiki page got updated, there is no need to maintain another **Supported APIs** in the readme.
Fixes #390 
There is no code change.
N/A

Issue 390: Update nodejs readme

---

.github/workflows/documentation.yml
nodejs/README.md

Update build script of Nodejs docs.
Fixes #400 
Update github workflow.
`documentation workflow should pass.

Issue 400: Update doc and its build for Nodejs

---

.github/workflows/debug.yml

Adds a github action to allow us to perform manual builds on the github actions host.

Debug: Add debug workflow

---

Cargo.toml
auth/Cargo.toml
book/src/index.md
channel/Cargo.toml
config/Cargo.toml
connection_pool/Cargo.toml
controller-client/Cargo.toml
examples/Cargo.toml
golang/Cargo.toml
macros/Cargo.toml
nodejs/Cargo.toml
pravegactl/Cargo.toml
python/Cargo.toml
retry/Cargo.toml
shared/Cargo.toml
wire_protocol/Cargo.toml

Update version to 0.3.3
Fixes #416
Update version to 0.3.3 to prepare for release.
All tests pass

Issue 416: Update version to 0.3.3

---

.github/workflows/cibuild.yml
.github/workflows/tagPublish.yml
python/pyproject.toml

Added `python 3.11` in bindings
Fixes #443
Added support for python 3.11
CI build should pass

Issue 443: Adding python support for 3.11

---

.github/workflows/publish_check.yml
.github/workflows/tagPublish.yml
Cargo.toml
auth/Cargo.toml
book/src/index.md
channel/Cargo.toml
config/Cargo.toml
connection_pool/Cargo.toml
controller-client/Cargo.toml
examples/Cargo.toml
golang/Cargo.toml
macros/Cargo.toml
nodejs/Cargo.toml
nodejs/package-lock.json
nodejs/package.json
pravegactl/Cargo.toml
python/Cargo.toml
retry/Cargo.toml
shared/Cargo.toml
wire_protocol/Cargo.toml

Update the rust client version to `0.3.5`
Fixes #446
Update rust client version to `0.3.5` for making new release
All tests should pass

Issue 446: Update version to 0.3.5

---

.github/workflows/publish_check.yml

updated the publish_check.yml to publish pravega-client
Fixes #455 
Updated the publish_check.yml to publish pravega-client
All tests should pass

Issue 455: Update github action to publish pravega-client

---

.github/workflows/publish_check.yml

Formatting the github action file publish_check.yml
Fixes #455 
After github action build complaining about workflow file "every step must define a `uses` or `run` key". So formatted the workflow file .
(Optional: steps to verify that the changes are effective)

Issue 455: Formatting publish_check.yml file
