benches/benchmark.rs
src/segment_reader.rs

Adds byte stream reader benchmark.
Removes `drain` operation as it involves memcpy that decreases the read performance significantly.
Improved performance snapshot:
10K ops, 100 Bytes payload
write: 20ms,
read: 5ms

Add byte stream reader benchmark and improve read performance

---

src/reactor/reactors.rs
src/reactor/segment_writer.rs

A false `ConditionalCheckFailed` returned due to reconnection. 
What happens is that when client sends an Event `e` to server and server has already accepted `e`, a reconnection is triggered before client receives the ack reply. The `e` is sent to server again due to reconnection so the ConditionalCheckFailed is returned since `e` has already been accepted before.
The temporary fix for this issue it to check if a reconnection happened right before receiving `ConditionalCheckFailed`. If it is then this error could be a false alarm and we can ignore it. However, this is not 100% guaranteed since another writer could write some data to the segment right at the reconnection session of our writer, and in that case the `ConditionalCheckFailed` is true. Right now …

Issue 198: ConditionalCheckFailed due to reconnection

---

controller-client/src/mock_controller.rs
integration_test/src/wirecommand_tests.rs
shared/src/lib.rs
src/reactor/segment_selector.rs
src/reader_group/reader_group_state.rs

Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>
Avoid a copy of the routing_key string on every write.
Borrows the ScopedSegment rather than performing a clone of the string.

Perf improvement: Avoid a copy of the routing_key string on every write.

---

integration_test/src/event_stream_reader_tests.rs
src/event_reader.rs
src/segment_slice.rs

Change `recv` to `try_recv` in `acquire_segment` method.
Fix #228 
`recv` will block forever if there is no slice for that reader. Use `try_recv` to let method return and caller can re-enter the method to acquire new segments.
Test should pass

Issue 228: Fix acquire segment

---

.github/workflows/python_test.yml
controller-client/Cargo.toml
controller-client/src/cli.rs
controller-client/src/lib.rs
controller-client/src/mock_controller.rs
controller-client/src/model_helper.rs
controller-client/src/paginator.rs
shared/src/lib.rs

- Enable List Streams Controller API on the Rust Client.
- Create a Paginator utility which returns a `impl Stream<Item = Result<String, RetryError<ControllerError>>>`  to handle huge stream lists with pagination.
- Enable List Streams option in the Controller CLI
Fixes #225 
- Enable controller api list streams which returns the streams for the provided scope and continuationToken.
```rust
async fn list_streams(&self, scope: &Scope, token: &str) -> ResultRetry<Option<(Vec<String>, String)>>;
```
- A paginator helper which returns an `impl Stream`  thereby lazily fetch the next page of streams from Pravega
```rust
pub fn list_streams(
scope: Scope,
client: &dyn ControllerClient,
) -> impl Stream<Item = …
```

Issue 225: Implement list streams controller API

---

config/src/credentials.rs
config/src/lib.rs
controller-client/src/lib.rs
wire_protocol/src/connection.rs

Currently token refresh is using a Runtime which makes it impossible to work in a async context. Use async way to refresh the token instead.
Fix #245 
Use async way to refresh token

Issue 245: Async token refresh

---

integration_test/src/byte_reader_writer_tests.rs
src/byte/writer.rs
src/event/transactional_writer.rs
src/event/writer.rs
src/segment/event.rs
src/segment/reactor.rs
src/segment/selector.rs
src/segment/writer.rs

support multiple segments in byte stream
Fix #262 
Add a `Option<ScopedSegment>` field in the `PendingEvent`. 
If the `Option` is not `None`, then `selector` will directly fetch the writer from the map using `segment` as a key.
Tests should pass

Issue 262: support multiple segments in byte stream

---

python_binding/tests/pravega_reader_test.py
python_binding/tox.ini
shared/src/lib.rs
src/event/reader.rs

Drop on EventReader should invoke readerOffline.
Fixes #200 
Drop on EventReader should invoke `reader_offline()`.
This is useful in scenarios where the Python user forgets to invoke reader offline. A scenario described in #257 is one instance of this.
With this change, `reader_offline()` is automatically invoked when the object is destructed.
```
In [11]: r1=rg.create_reader("r1")
May 14 18:54:41.627  INFO pravega_client::stream_reader_group: Creating reader "r1" under reader group "rg2"
May 14 18:54:41.627  INFO pravega_client::event::reader_group_state: Adding reader Reader { name: "r1" } to reader group
In [12]: r1=rg.create_reader("r2")
May 14 18:54:47.361  INFO pravega_client::stream_reader_group: …
```

Issue 200: Drop on EventReader should automatically invoke reader offline API.

---

config/Cargo.toml
integration_test/Cargo.toml

Reqwest is using openssl by default, we can change it to use rustls.
Fix #274
Use rustls instead of openssl.
current test should pass

Issue 274: Remove openssl

---

book/src/Python/PythonBindings.md
config/src/lib.rs
connection_pool/src/connection_pool.rs
controller-client/src/cli.rs
controller-client/src/lib.rs
integration_test/src/event_writer_tests.rs
integration_test/src/table_tests.rs
python_binding/README.md
python_binding/src/stream_manager.rs
python_binding/src/stream_reader.rs
python_binding/src/stream_reader_group.rs
python_binding/src/stream_writer.rs
python_binding/tests/pravega_client_test.py
python_binding/tests/pravega_reader_test.py
shared/Cargo.toml
shared/src/lib.rs
src/client_factory.rs
src/event/reader.rs
src/event/transactional_writer.rs
src/segment/metadata.rs
src/sync/synchronizer.rs

* allow scheme to be included in PravegaNodeUri
* changes ClientConfigBuilder to automatically set `is_tls_enabled = true` when uri scheme is 'tls'
* allows tls scheme to be used with StreamManager Python client when tls_enabled default value (false) is used
Fixes #247 
changes to shared/lib
* accepts schemes in PravegaNodeUri
* added PravegaNodeUriParseError
* added PravegaNodeUri::is_well_formed static method
* added PravegaNodeUri::uri_parts_from_string static method
* changed existing methods to use uri_parts_from_string
changes to config/lib
* added default builder for `ClientConfigBuilder::is_tls_enabled`
* altered `ClientConfigBuilder::extract_trustcerts` to also call `default_is_tls_enabled` (builder …

Issue 247: Accept scheme in controller URI

---

integration_test/src/byte_reader_writer_tests.rs
src/byte/reader.rs

Add sync and async current_head and current_tail methods.
Fix #293 
Add both sync and async for those methods

Issue 293: Add sync and async to byte reader current_head and curernt_tail

---

.github/workflows/build_wheel.py
.github/workflows/documentation.yml
.github/workflows/python_test.yml
.github/workflows/tagPublish.yml
python_binding/Cargo.toml
python_binding/pyproject.toml

Signed-off-by: Sandeep <sandeep.shridhar@emc.com>
Update maturin tool from 0.8.3 to 0.11.0
Fixes #269 
Update maturin tool from `0.8.3` to `0.11.0`.
Verified that the python packages generated with the latest version of maturin are manylinux compliant. Non compliant whl packages cannot be uploaded to pypi repository. The fix of removing open ssl dependency simplified this upgrade.
All the existing tests should continue to pass.

Issue 269: Update maturin.

---

integration_test/src/transactional_event_writer_tests.rs
shared/src/naming_utils.rs
src/segment/writer.rs

The hexadecimal based transaction id was using upper case letter whereas lower case letter should be used.
use lower case letter
test should pass

Issue 292: Fix transaction id format error

---

config/Cargo.toml
integration_test/Cargo.toml

Use native roots for reqwest which will auto scan the default linux cert directory. Previously, it is using root certs from webpki, so any self signed certs cannot be loaded. 
Fix #301
Use native roots
Had verified that it's working in SDP

Issue 301 : Use native roots for reqwest

---

shared/Cargo.toml

Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>
Prevent a compile error. 
Fixes #329 
Enable dangerous feature flag on rustls to prevent a compile error. (Dangerous configuration is only enabled if explicitly set in client config)

Issue 329: Enable dangerous feature flag

---

src/segment/event.rs
src/segment/reactor.rs
src/segment/writer.rs

Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>
Support reconnecting when a connection was never established
Fixes #286
Allows for no connection to be specified in a re-connect request. Meaning the reconnect should be attempted if there is no connection.

Issue 286: Support reconnecting when a connection was never established

---

src/segment/metadata.rs
src/test_utils.rs

Signed-off-by: dellThejas <Thejas.Vidyasagar@dell.com>
- Added `is_sealed` getter to check if the segment has been sealed.
Fixes #226 
Provides the user with information whether the segment is sealed or not.
Existing tests continue to pass.

Issue 226: Add is_sealed getter in metadata

---

.github/workflows/publish_check.yml
.github/workflows/tagPublish.yml
examples/Cargo.toml
macros/README.md
pravegactl/Cargo.toml

* Automate cargo publish check for github tags.
* Ensure python bindings are published only on release tags.
* Add the missing ReadMe.md
Fixes #337
* Automate cargo publish check for github tags.
* Ensure python bindings are published only on release tags.
* Add the missing ReadMe.md
All the existing tests should continue to pass.
https://github.com/pravega/pravega-client-rust/runs/4234022838?check_suite_focus=true verifies that this automation works.

Issue 337: Automate cargo publish check

---

src/byte/reader.rs

Clarify that Reader does not actually implement the standard io traits.
No code change

Issue 343: Update Byte client doc comment

---

python/src/stream_manager.rs

Fix the Wrong retention type in Python binding. `StreamRetentionPolicy.by_time()` should create a `Retention` with type `RetentionType::Time`.
Fixes #350 
Change `RetentionType::Size` to `RetentionType::Time`. Also fix some typos in the Python doc.
`cargo build` passes.

Issue 350: Wrong retention type in Python binding

---

nodejs/README.md
nodejs/native_cjs.ts
nodejs/native_esm.ts
nodejs/src/lib.rs
nodejs/src/stream_manager.rs
nodejs/stream_manager.ts
nodejs/tests/client.test.ts

Add delete_reader_group function in nodejs client.
Fixes #368 
Wrap the rust `delete_reader_group`.
nodejs/tests/client.test.ts with new `stream_manager.delete_reader_group(SCOPE, reader_group_name);` should pass without error.

Issue 368: Nodejs client should have a delete_reader_group function

---

.github/workflows/tagPublish.yml

Create the Github release page on tag push via Github actions so the native node addon can be uploaded.
Fixes #389 
Create the Github release page on tag push via Github actions so the native node addon can be uploaded.
This release is created automically through the new workflow.
https://github.com/thekingofcity/pravega-client-rust/releases/tag/v0.7.5

Issue 389: Create release page on tag push

---

.github/workflows/cibuild.yml

Fix PR build steps that are failing due to disk space issues.
Issue TBD
Adds maximize-build-space GitHub Action to CIbuild workflow steps that are failing to build in PRs.
All steps on this PR should pass.

Use maximize-build-space Action in CIbuild workflow

---

.github/workflows/tagPublish.yml

Signed-off-by: qian1166 <78283846+qian1166@users.noreply.github.com>
CVE-2015-20107 security related issues need to upgrade python to the latest version
Added Python 3.10 in tagPublish.yml

Added Python 3.10 in tagPublish.yml

---

.github/workflows/cibuild.yml
.github/workflows/documentation.yml
.github/workflows/python_test.yml
config/src/connection_type.rs
config/src/lib.rs
controller-client/src/lib.rs
controller-client/src/test.rs
integration_test/build.rs
integration_test/src/disconnection_tests.rs
integration_test/src/event_reader_tests.rs
integration_test/src/index_stream_tests.rs
integration_test/src/lib.rs
integration_test/src/pravega_service.rs
integration_test/src/reader_group_tests.rs
integration_test/src/wirecommand_tests.rs
nodejs/src/lib.rs
python/src/lib.rs
retry/src/lib.rs
retry/src/retry_async.rs
retry/src/retry_policy.rs
retry/src/retry_result.rs
retry/src/retry_sync.rs
src/event/reader.rs
src/event/reader_group_state.rs
src/index/reader.rs
src/lib.rs
src/sync/table.rs
wire_protocol/src/mock_connection.rs

Fixes the Test suit job intermittently timeout problem. also fixes Clippy related issues like duplicate default method etc.
Purpose of the change
Fixes #395 #404 
The code does following :-
1- Creates a internal function reader_offline.
2- Calls that method inside one of thread in the destructor.
3- Initializes the values of readerState to default
4- Drops the unused lock (which was causing the deadlock) 
5- Fixes the clippy related issue by following the clippy rules
This can be verified on local by running following 
```
cargo fmt --check --all
cargo clippy --workspace
cargo test -p pravega-connection-pool -p pravega-client-channel -p pravega-controller-client -p pravega-client-integration-test -p …
```

Issue 395: Fix Test Suite job intermittently timeout Problem and Clippy related issues.

---

.github/workflows/build_wheel.py
.github/workflows/cibuild.yml
.github/workflows/documentation.yml
.github/workflows/publish_check.yml
.github/workflows/python_test.yml
.github/workflows/tagPublish.yml
python/Cargo.toml
python/pyproject.toml
python/tox.ini

- Updates maturin to >=0.14,<0.15. This requires to fix the incompatible linux tag in python wheel.
- Removes support for python 3.6 as it's near EOL and many dependencies dropped support for it. 
- Maturin has dropped support python 3.6 since 0.13.0 - https://github.com/PyO3/maturin/releases/tag/v0.13.0
- Adds `manylinux_2_35` to the python wheels as a name tag to make them compatible with pypi.
- Installs specific version of tox==3.28.0 and also tox-pyo3.
- Fixes Cargo release issue.
Fixes #418, #420, Closes #378 
- All the CI should run successfully.
- Once a tag is created wheels should be uploaded to pypi.

Issue 418:  Update maturin,tox; Removes python 3.6 and fix crate, pypi related GA

---

.github/workflows/publish_check.yml

- Cargo release is a dry-run by default even if `dry-run` is not mentioned explicitly.
- To make it an actual release, we have to provide `-x` or `--execute` flag in the command.
- Fixes other cargo release related errors.
Fixes #425 
- Adds `-x` flag in the `publish_check.yml` workflow.
- Verified it on the forked repo. https://github.com/kotlasaicharanreddy/pravega-client-rust/actions/runs/4946424072/workflow

Issue: 425 Adds -x (--execute) flag to cargo release.

---

integration_test/src/pravega_service.rs

When running the standalone it throws an NPE repeatedly.
Fixes #428 
The actual property what is being read in Pravega standalone is "security.auth.credentials.pwd" but while running rust client integration test cases it was being set as "singlenode.security.auth.credentials.password" because of which the password credentials was being set as empty.
Below error should not be coming in the test logs.
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated@450526dd
java.lang.NullPointerException: startCall() returned a null listener for method io.pravega.controller.stream.api.grpc.v1.ControllerService/getCurrentSegments

Issue 428: Correcting the password credentials in standalone properties

---

.github/workflows/nodejs_test.yml
.github/workflows/tagPublish.yml

According to the [README](https://github.com/nodejs/Release/blob/b4b46113a259b19db074a7fd47b552d84c0883f4/README.md) of node/release, 12 and 14 are no longer supported. We need to maintain versions 16, 18, and 20.
Fixes #423
Update nodejs version to 16, 18, and 20.
.github\workflows\nodejs_test.yml should pass.

Issue 423: Update node version for prebuilt binary

---

.github/workflows/publish_check.yml

- Adds `--no-confirm` flag to the cargo release command.
Fixes #430 
- Makes the cargo release non-interactive.
- All github actions should pass.

Issue 430: Make cargo release non-interactive.

---

.github/workflows/publish_check.yml

- A token named `CARGO_REGISTRY_TOKEN` is required for the publishing of rust artifacts to the repository. 
- This pr address by adding the above mentioned token in the `publish_check.yaml` which triggeres the release of rust to crate.io repository.
Fixes #432 
- Add CARGO_REGISTRY_TOKEN secret
- All tests and github actions should be green.
- Whenever a new tag/release is created, rust artifacts/release should be published to crates.io repository.

Issue 432: Adds CARGO_REGISTRY_TOKEN secret in publish_check.yaml

---

config/Cargo.toml

- wildcard (*) dependency constraints are not allowed on crates.io.
- So, removed (*) wildcard and added the lastest version of serial_test:v2.0.0
Fixes #434 
**What the code does** 
- Adds v2.0.0 to the serial_test
- All github actions should pass.
- Once a tag/release is created, then rust artifacts should be published to crates.io

Issue 434: Removes wildcard (*) dependency constraints 

---

.github/workflows/publish_check.yml

Updated the publish_check.yml to publish pravega-client
Fixes #455 
Running publish command for different packages separately.
All test should pass.

Issue 455: correcting publish run command
